name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency: ci-${{ github.event_name == 'push' && 'main' || github.head_ref }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - if: ${{ github.event_name == 'pull_request' }}
        run: bun biome:check
      - run: bun test
  build-and-publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write      
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run export
      - run: git rev-parse --short HEAD > public/commit.txt
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy public/ --project-name=ascrazy-me --branch=${{ github.event_name == 'push' && 'main' || github.head_ref }}
